### ISSUE TITLE
Support für PushTAN 2.0 (Decoupled Verfahren)

### ISSUE THREAD

**Issue by danielr1996** [hbci4j/hbci4java#74]
I noticed that in order to access all statements (Umsätze) I need to provide an actual TAN consisting of six digits and displayed in the S-Push TAN app, whereas when viewing all statements on the Sparkasse Webinterface I can just swipe in the app to confirm the action. 

Is this something hbci4j can also support, or is this simply not supported with the hbci api? A few years ago I tried implementing a hbci client myself in nodejs (boy is that an ugly API) and I remember that there were different numerical codes to request different tan schemas, e.g. comdirect supported smstan or phototan. If I remember correctly there was also a method to request the available tan methods from the api. 

From a developer perspective this would be way more easy to implement as I wouldn't need to implement means of supplying the tan but can just wait for the user to confirm the request in the app.

**Comment by willuhn** [comment]
Du kannst hier auf Deutsch schreiben. FinTS wird ohnehin nur in Deutschland verwendet.
Dieses neue TAN-Verfahren nennt sich "PushTAN 2.0" - bzw. laut offizieller Spezifikation "Decoupled-Verfahren". Per Webseite unterstützen es schon viele Banken, per FinTS nach meinem Wissen bisher nur die Sparkassen. Voraussetzung für den Support in FinTS ist die Unterstützung von HKTAN in Version 7 (ist bereits in HBCI4Java enthalten). Damit es genutzt werden kann, muss aber noch das eigentliche Austauschverfahren implementiert werden, wie unter https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2020-07-10_final_version.pdf in Kapitel B.4.2.2 beschrieben. Das ist in HBCI4Java bisher noch nicht umgesetzt. Im Prinzip muss hier eine Funktion implementiert werden, die in einem separaten Thread mit der laufenden FinTS-Session bei der Bank pollt, ob die Freigabe durch den User bereits erfolgt ist. Währenddessen muss der Main-Thread mit der eigentlichen Ausführung des Geschäftsvorfalls pausiert werden. Nach der Rückmeldung der Freigabe über den zweiten Thread kann der Main-Thread dann fortsetzen. Ist wie gesagt noch nicht implementiert.

**Comment by willuhn** [comment]
Das Thema ist leider nicht einfach mit einem weiteren Callback umgesetzt. Wie ich schon schrieb: An der Stelle muss ein Multi-Threading eingebaut werden, um parallel in einem zweiten Thread HBCI-Nachrichten für das Status-Pollen senden zu können, während der Haupt-Thread wartet.

Ich lasse das Issue mal offen.

**Comment by DominikHolzapfel** [comment]
Hallo,
ich bin im Rahmen eines Tests auf dieses Problem gestoßen. Im Zuge dessen habe ich mir angeschaut, wie Banking4 von Subsembly dieses Problem löst.
Nachdem eine Transaktion angestoßen wird, wartet die Anwendung auf die Bestätigung des Nutzers (manuell per Knopfdruck), dass die Freigabe in der App erfolgt ist. Daraufhin wird ein Request mit einem HKTAN Request zum Server gesendet, um den Status der Transaktion zu prüfen. Sollte die Freigabe in der App tatsächlich erfolgt sein, geht der Flow weiter, ansonsten kommt derselbe Dialog einfach zurück und der Nutzer wird erneut aufgefordert, "Ok" zu drücken.

Ist mit so einem Vorgehen noch Multi-Threading notwendig? Oder wäre es mit expliziter Nutzer-Eingabe eventuell einfacher?

Ich kann auch gerne Beispiel Request/Response Paare zur Verfügung stellen, falls das hilft.

**Comment by willuhn** [comment]
Hatte vergessen, das Ticket zu schliessen. Ist seit 22.12.2023 mit HBCI4Java 3.1.74 umgesetzt. Es gibt hierzu einen neuen Callback NEED_PT_DECOUPLED, der im HBCICallback implementiert werden muss. Dieser muss lediglich einen Warte-Dialog mit der Message der Bank anzeigen sowie einen OK-Button, auf den der User klicken soll, sobald er die Freigabe in der Push-TAN-App durchgeführt hat.

**Comment by willuhn** [comment]
Für's Protokoll noch die damit verbundenen Commits:

- https://github.com/hbci4j/hbci4java/commit/555dde8f7080e003b2049212e9c35bb2f7f53b80
- https://github.com/hbci4j/hbci4java/commit/ad5183f662c1aa850610d6f69a4ead79b2f8d2aa
- https://github.com/hbci4j/hbci4java/commit/ead6f37d68adaf411a02e8c1ffeb1cb3afbf4412
- https://github.com/hbci4j/hbci4java/commit/34fd25668f80028c725d38dc08a446127c2be032
- https://github.com/hbci4j/hbci4java/commit/4cabd5487ff702dc0b2ee583710cabfca757988a

**Comment by rlill** [comment]
Vielen Dank für die Umsetzung des Decoupled Verfahrens.
Gibt es ein Beispielprogramm, wie es genutzt werden kann?
examples/UmsatzAbrufPinTan.java ist 6 Jahre alt und bilded diesen Fall nicht ab.

Ich scheitere mit meiner Implementierung einer Umsatzabfrage. Habe schon verschiedene Werte für 'secmech' probiert (921, 923) und den case in den Callback eingefügt. Bekomme von der Sparkasse immer noch keine Daten. Vor der Umstellung auf PushTan hat das funktioniert (mit ChipTan).
Irgendein Tipp, was ich falsch mache?

07:58:12,208 INFO  Kontoauszug::log (Kontoauszug.java:382) - have to create new passport file
07:58:12,916 INFO  Kontoauszug::log (Kontoauszug.java:382) - the job with the code HNSHK seems not to be allowed with PIN/TAN
07:58:12,916 INFO  Kontoauszug::log (Kontoauszug.java:382) - the job with the code HKIDN seems not to be allowed with PIN/TAN
07:58:12,916 INFO  Kontoauszug::log (Kontoauszug.java:382) - the job with the code HKVVB seems not to be allowed with PIN/TAN
07:58:12,916 INFO  Kontoauszug::log (Kontoauszug.java:382) - the job with the code HKSYN seems not to be allowed with PIN/TAN
07:58:14,580 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9050:Die Nachricht enthält Fehler.
07:58:14,580 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9800:Dialog abgebrochen
07:58:14,580 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9930:Kein gültiges Sicherheitsprofil.
07:58:14,746 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9050:Die Nachricht enthält Fehler.
07:58:14,746 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9800:Dialog abgebrochen
07:58:14,746 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9010:Die angegebene Bankreferenz/Dialog-ID ist nicht gültig.
07:58:14,746 INFO  Kontoauszug::log (Kontoauszug.java:382) - Meldung der Bank: 9010:Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. (3: TanMedia.TANMediaList4)
07:58:14,910 ERROR Kontoauszug::main (Kontoauszug.java:320) - org.kapott.hbci.exceptions.HBCI_Exception: can not create HBCI handle
org.kapott.hbci.exceptions.HBCI_Exception: can not create HBCI handle
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:183)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:116)
	at rlill.kontoauszug.Kontoauszug.main(Kontoauszug.java:179)
Caused by: org.kapott.hbci.exceptions.HBCI_Exception: can not register user
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:298)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:166)
	... 2 more
Caused by: org.kapott.hbci.exceptions.HBCI_Exception: error while fetching UPD
	at org.kapott.hbci.manager.HBCIUser.fetchUPD(HBCIUser.java:657)
	at org.kapott.hbci.manager.HBCIUser.sync(HBCIUser.java:696)
	at org.kapott.hbci.manager.HBCIUser.register(HBCIUser.java:721)
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:296)
	... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:1001)
	at java.base/java.lang.StringBuffer.replace(StringBuffer.java:497)
	at rlill.kontoauszug.Kontoauszug$MyHBCICallback.callback(Kontoauszug.java:581)
	at org.kapott.hbci.passport.AbstractPinTanPassport.getTanMedia(AbstractPinTanPassport.java:1772)
	at org.kapott.hbci.passport.AbstractPinTanPassport.getSCARequest(AbstractPinTanPassport.java:594)
	at org.kapott.hbci.passport.AbstractPinTanPassport.checkSCARequest(AbstractPinTanPassport.java:425)
	at org.kapott.hbci.passport.AbstractPinTanPassport.onDialogEvent(AbstractPinTanPassport.java:259)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:92)
	at org.kapott.hbci.manager.HBCIUser.fetchUPD(HBCIUser.java:639)
	... 6 more

**Comment by willuhn** [comment]
Das ist eine NullPointerException in deinem eigenen Code:

Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at java.base/java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:1001)

Wende dich bei User-Support bitte an die Mailingliste unter https://groups.google.com/forum/?hl=de#!forum/hbci4java - siehe auch https://github.com/hbci4j/hbci4java
